<?php

define('IFMGA_GROUP_ID', 13);
define('IFMGA_MESSAGE_TEMPLATE', 64);
define('PARTICIPANT_STATUS_UNDER_REVIEW', 30);
define('PARTICIPANT_STATUS_ENROLLED_PENDING_PAYMENT', 30);
define('UNDER_REVIEW_MSG_TPL', 69);
define('EPP_LESS_MSG_TPL', 73);
define('EPP_GREATER_MSG_TPL', 70);


?>