<?php

define('IFMGA_GROUP_ID', 13);
define('IFMGA_MESSAGE_TEMPLATE', 64);
define('PARTICIPANT_STATUS_UNDER_REVIEW', 35);
define('PARTICIPANT_STATUS_ENROLLED_PENDING_PAYMENT', 32);
define('PARTICIPANT_STATUS_ENROLLED_PENDING_PAYMENT2', 33);
define('PARTICIPANT_STATUS_PASS', 16);
define('PASS_MESSAGE_TEMPLATE', 64);
define('UNDER_REVIEW_MSG_TPL', 69);
define('UNDER_REVIEW_MSG_TPL_ADMIN', 80);
define('EPP_LESS_MSG_TPL', 73);
define('EPP_GREATER_MSG_TPL', 70);
define('ENROLLMENT_DATE_FIELD_ID', 127);
define('TUITION_FIELD_ID', 128);

?>